### ISSUE TITLE
Using tabs for indentation

### ISSUE THREAD

**Issue by DougBeney** [fgallina/python.el#163]
Hello,
Not sure if it's still ok to post issues & questions here being that this repo is unmaintained. Not sure where else to post it though.

Is there an easy way to enable tabs for indentation with this package? It seems to overwrite my settings to comply with PEP8 and I am not able to fix this through a hook.

This is the snippet I am attempting to use.

    (add-hook 'python-mode-hook
	    (lambda ()
		    (setq-default indent-tabs-mode t)
		    (setq-default tab-width 4)
		    (setq-default py-indent-tabs-mode t)
	    (add-to-list 'write-file-functions 'delete-trailing-whitespace)))

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report any issues using the Emacs command:

M-x report-emacs-bug

I believe this particular issue has already been reported here, however:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32876

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
